_BASE_: "Base-Panoptic-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 101
  MASK_ON: True
SOLVER:
  # STEPS: (40000, 55000)
  # MAX_ITER: 65000
  STEPS: (24000, 33000)
  MAX_ITER: 39000
DATASETS:
  TRAIN: ("cityscapes_train_separated",)
  TEST: ("cityscapes_val_separated",)
# ref: pointrend_semantic_R_101_FPN_1x_cityscapes.yaml
INPUT:
  FORMAT: "RGB"
  # MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536, 1792, 2048)
  MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
  # COLOR_AUG_SSD: True
VERSION: 2
