_BASE_: "Base-Panoptic-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (40000, 55000)
  MAX_ITER: 65000
# ref: pointrend_semantic_R_101_FPN_1x_cityscapes.yaml
INPUT:
  FORMAT: "RGB"
  # MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536, 1792, 2048)
  # MIN_SIZE_TRAIN: (512, 768, 1024, 1280)
  # MIN_SIZE_TRAIN_SAMPLING: "choice"
  # MIN_SIZE_TEST: 1024
  # # MAX_SIZE_TRAIN: 4096
  # MAX_SIZE_TEST: 2048
  # CROP:
  #   ENABLED: True
  #   TYPE: "absolute"
  #   SIZE: (512, 1024)
  # # COLOR_AUG_SSD: True